#!/bin/bash

#set -e

ROOT_DIR=$PWD
TOOLS_DIR=${ROOT_DIR}/pctools
OUT_DIR=${ROOT_DIR}/out
export PATH=${TOOLS_DIR}/linux/mod_update:${TOOLS_DIR}/linux/eDragonEx:${TOOLS_DIR}/linux/fsbuild200:${TOOLS_DIR}/linux/openssl:$PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:${TOOLS_DIR}/linux/libs
DEBUG_VERSION=release

show_help()
{
printf "
NAME
    pack-new - The pack tools for linux firmware

SYNOPSIS
    pack [-h] [-b board]

OPTIONS
    -h                  Display help message
    -b [board_type]     Board type, e.g. E72 
    -c [custom]         custom board,e.g HYT,LILIN
"
}

while getopts hc:p:b:B:d:f: OPTION
do
    case $OPTION in
    h) show_help
    exit 0
    ;;
    
    b) PACK_BOARD=$OPTARG
    ;;
    
    c) CUSTOM_INFO=$OPTARG
    ;;
    
  	d) DEBUG_VERSION=$OPTARG
    ;;
  
    *) show_help
    exit 0
    ;;
esac
done


do_prepare()
 {
    if [ -d ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD ]; then
        rm -rf ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD/
    fi
    mkdir -p ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD/   
}


do_pack_linux()
{
    printf "!!!Packing for linux!!!\n"
		
		cp -v pack_src/$CUSTOM_INFO/$PACK_BOARD/kernel/uImage ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD/boot.fex
    cp -v pack_src/$CUSTOM_INFO/$PACK_BOARD/boot/boot0_spinand.bin ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD/boot0_spinand.fex
    cp -v pack_src/$CUSTOM_INFO/$PACK_BOARD/boot/u-boot.bin ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD/u-boot.fex
   	cp -v pack_src/$CUSTOM_INFO/$PACK_BOARD/boot/boot0_spi_nand_burn.bin ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD/boot0_spi_nand_burn.fex
	  
		cp -v pack_src/$CUSTOM_INFO/$PACK_BOARD/config/* ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD/
		mv ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD/sys_partition_spi_nand_linux.fex ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD/sys_partition.fex
		mv ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD/boot_logo.JPG ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD/boot_logo.fex
		if [ "release" == ${DEBUG_VERSION} ]; then
	 	 cp pack_src/$CUSTOM_INFO/$PACK_BOARD/config/env_release.cfg ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD/env.cfg
	  fi
	  
	  if [ "debug" == ${DEBUG_VERSION} ]; then
	 	 cp pack_src/$CUSTOM_INFO/$PACK_BOARD/config/env_nfs.cfg ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD/env.cfg
	  fi	
    
		
    cd ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD/
		 
  	busybox unix2dos sys_config.fex
  	busybox unix2dos sys_partition.fex
  	printf "!!!script script!!!\n"
  	script sys_config.fex
		script sys_partition.fex
		printf "!!!script script!!!\n"
		 
    cp sys_config.bin  config.fex
		
		update_boot0 boot0_spinand.fex	sys_config.bin SDMMC_CARD 
		update_uboot u-boot.fex  sys_config.bin
		
		
		sunxi_env_gen env.cfg env.fex 
		
    update_mbr sys_partition.bin  1
		
		rm ./sys_config.*
		rm ./sys_partition*
		rm ./*.cfg
		rm config.fex
		rm dlinfo.fex
		
    
    mkyaffs2image ${ROOT_DIR}/pack_src/$CUSTOM_INFO/$PACK_BOARD/rootfs ${OUT_DIR}/$CUSTOM_INFO/output_$PACK_BOARD/rootfs.fex
        
    printf "pack finish\n"
}

show_help
do_prepare
do_pack_linux
